### ISSUE TITLE
Dictionary AttributeError in score_utils.py (Python3 Related)

### ISSUE THREAD

**Issue by nathanmlim** [open-forcefield-group/smarty#199]
When trying to use smirky from the command line, I encountered this error:
```
File "/home/nathanlim/anaconda3/envs/icebox/lib/python3.5/site-packages/smarty/score_utils.py", line 53, in load_trajectory
    if not timeseries.has_key( iteration): timeseries[iteration] = {}
AttributeError: 'dict' object has no attribute 'has_key'
```
According to the [docs](https://docs.python.org/3.1/whatsnew/3.0.html#builtins) 'has_key' was removed with Python 3

> Removed. dict.has_key() – use the in operator instead.

**Comment by davidlmobley** [comment]
@bannanc - can you have a look? I think in python3 this would be `if not iteration in timeseries`, which I believe also works in python2.7.

@limn1 - it also might be good to update me on Slack what you're doing with Smirky, as it's not totally obvious to me and I'm curious. :)

**Comment by bannanc** [comment]
@limn1 - I'm also curious what you're doing with smirky?

@davidlmobley - I'll fix this and double check we aren't using similar dictionary checks. I thought I had a test for all the functions I wrote, but I must have missed some of them in score_utils, so I'll look into that as well.

**Comment by davidlmobley** [comment]
He was just trying the example for fun, @bannanc . :)

**Comment by bannanc** [comment]
see pull request #200

**Comment by bannanc** [comment]
Fixed with pull request #200
